name: Python CI with Tox
on:
  push:
    branches:
      - main
      - develop
      - temp

jobs:
  toxic-test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build toxic image
        run: docker build --tag toxic -f Dockerfile.tox .
      - name: run toxic image
        run: docker run --rm  -v /var/run/docker.sock:/var/run/docker.sock toxic tox
